### ISSUE TITLE
Getting some errors in reframe and reagent

### ISSUE THREAD

**Issue by dhirensr** [oliyh/re-learn#22]
I used the project in my application. It shows errors on my terminal 
 -> Use of undeclared Var reagent.ratom/add-on-dispose! at line 32 resources/public/js/compiled/out/re_frame/interop.cljs

My code used is: 
 
(def re-learn-component
 (re-learn/with-lesson
   {:id :basic-lesson
    :description "Just testing how to use re-learn"
    :position :bottom}
   (fn []
     [:div
      [:div.h3
       [:h3 "Ich bin Dhiren Serai"]]])))

(def check-re-learn
 (re-learn/with-tutorial
   {:id :test-tutorial
    :name "check list"
    :description "create your learning components"
    :lessons [{:id :willkommen
               :description [:div
                             [:h2 "Welcome"]]}
              re-learn-component]}
   (fn []
     [:div
      [:h5 "Hallo"]
      [re-learn-component]])))

(defn mount-root
 ;;;Start of the application
 []
 (re-learn/init)
 (r/render [check-re-learn] (by-id "test")))

(.addEventListener js/document "deviceready"
                  mount-root
                  false)

**Comment by oliyh** [comment]
Hi,

What versions of reagent and re-frame are you using?

Cheers

**Comment by dhirensr** [comment]
Hey, using reagent "0.6.0-alpha" in my project! I dont have re-frame in my project!

**Comment by dhirensr** [comment]
Hey i used re-frame "0.8.0" in my project and it worked!

**Comment by oliyh** [comment]
I guess you must have had an older version of re-frame pulled in via some
transitive dependency. Thanks for the update and glad it works now!

Oliy
