### ISSUE TITLE
Re-learn usage across different pages

### ISSUE THREAD

**Issue by dhirensr** [oliyh/re-learn#23]
I used re-learn in my application on a single page and its working fine.
But can I use it across different pages ,like for example on a particular page change different tutorials should show up on start and on other page different tutorial should be triggered depending on the click of the first page in which there are two buttons.
like the tutorial should continue between different pages? Is this possible use-case with relearn?

**Comment by oliyh** [comment]
Hi,

I haven't tried it but yes I think it should be possible to continue one
tutorial across two pages (components) if you use the same tutorial-id on
each of them.

Oliy

**Comment by dhirensr** [comment]
But I can only use render when the application starts ,I want the application to use 
(r/render [relearn-tutorial] (u/by-id "container"))
 (r/render [re-learn-views/tutorial {:context? false}] (u/by-id "tutorial"))
only when the page is switched, and it shows a weird error.
by the  way i can't use [tutorial] as a component? it only gets triggered on r/render that's the problem

**Comment by oliyh** [comment]
You're meant to just mount the re-learn layer once for the application (i.e. outside of any routing you might have):
```clj
(reagent/render [re-learn-views/tutorial-view {:context? true}] tutorial-root)
```

And then it will take care of displaying the correct tutorial at the right time. If you have a tutorial that spans two pages I would suggest the following:

1. Define your tutorial once as data
```clj
(def my-tutorial
    {:id          :checkout-tutorial
     :name        "The checkout"
     :description "Review your basket, check the price and confirm your purchase"
     :precedence  1 ;; optional, allows some tutorials to take precedence over others
     :lessons [{:id          :welcome-lesson ;; this is an inline lesson, not attached to anything
                     :description "Welcome to the re-learn example"}
                    basket
                    totals
                    purchase-button]})
```

2. Use the tutorial on two different pages

```clj
(def page-one
  (re-learn/with-tutorial my-tutorial
    (fn [] ...)))

(def page-two
  (re-learn/with-tutorial my-tutorial
    (fn [] ...)))
```

I hope I've understood what you're trying to do, and that this helps?

Oliy

**Comment by dhirensr** [comment]
I want to use it conditionally across two pages something like this,
```
(def purchase-button
  (re-learn/with-lesson
    {:id          :purchase-button-lesson
     :description "When you're ready, click here to purchase"
     :position    :bottom                  

     :attach      [:button#some-id]       
     :continue    {:event :click           ;; optional, continue when this event occurs
                   :event-filter (fn [e] (.click (jq/$ "some-id" #(swap! assoc state :test true)}}

    (fn [] [:button.mdl-button.mdl-button--raised "Purchase"])))
(def my-tutorial
    {:id          :checkout-tutorial
     :name        "The checkout"
     :description "Review your basket, check the price and confirm your purchase"
     :precedence  1 ;; optional, allows some tutorials to take precedence over others
     :lessons [{:id          :welcome-lesson ;; this is an inline lesson, not attached to anything
                :description "Welcome to the re-learn example"}
            (if (:test @state)
                basket)
                totals
                purchase-button]})
```
But what is happening is because of ``` (reagent/render [re-learn-views/tutorial-view {:context? true}] tutorial-root) ``` my app is already loaded with all these tutorials so the order isn't changed conditonally
Is it possible to make it conditional? I see precedence option is not mentioned in the Readme File are there any more options which I could use to make this happen?

Thanks for replying.

**Comment by oliyh** [comment]
Hi,

Currently no, that won't work - the lessons and tutorials are expected to just be data that is evaluated at compile time.

One thing that might help is that lessons only appear when their parent - i.e. the component they are attached to - is visible (is being rendered by React). So, you could attach the `basket` lesson to something which will appear or disappear depending on your `:test true` test:

```clj
(def basket
  (re-learn/with-lesson
    {...}
    [:div "This is the basket"]))

(defn checkout []
  (re-learn/with-tutorial
    {:lessons [basket
               something-else]
     ...}
  (let [show-basket? (atom false)]
    (fn []
      (when @show-basket?
        [basket])
      [something-else]))))
```

The implementation relies on the React lifecycle functions, so one other way to achieve it would be to try registering your own `:component-will-mount` functions to maybe mutate the lessons in the re-frame database based on your criteria. This would be quite brittle however.
