### ISSUE TITLE
Can't exeute the example

### ISSUE THREAD

**Issue by punit-naik** [oliyh/re-learn#26]
I am not able to execute the code in the checkout example. Below is the error I am getting:
[re-learn-error](https://ibb.co/gVV1YV)

**Comment by ggeoffrey** [comment]
Might be related to #24 ?

**Comment by punit-naik** [comment]
@ggeoffrey Thanks! As mentioned in #24 , upgrading `re-learn` to `0.1.2-SNAPSHOT` worked!

**Comment by oliyh** [comment]
Hi I have released a new version that includes #24, sorry for the confusion.
